In [2]:
import pandas as pd

co2Link='https://github.com/CienciaDeDatosEspacial/dataSets/raw/main/co2.csv'
forestLink='https://github.com/CienciaDeDatosEspacial/dataSets/raw/main/forestRev.csv'

co2=pd.read_csv(co2Link)
forest=pd.read_csv(forestLink)

In [16]:
co2.columns,forest.columns

(Index(['name', 'co2', 'co2_date', 'region'], dtype='object'),
 Index(['Country', 'ForestRev_gdp', 'ForestRev_date'], dtype='object'))

In [15]:
co2.shape,forest.shape

((218, 4), (204, 3))

## Option 1: 
Keeping only rows with what is common in both key columns (name and Country)

In [115]:
# inner: use intersection of keys from both frames (DEFAULT)
# left_on: Column or index level names to join on in the left DataFrame.
# right_on: Column or index level names to join on in the right DataFrame

cia=co2.merge(forest,how='inner',left_on='name',right_on='Country')
cia.shape

(197, 7)

## Option 2: 
Keeping all rows from one dataframe. If a key value does not find a match, the value is kept, but the columns will have missing values.

In [21]:
# left: Keeping all rows from left Dataframe

co2.merge(forest,how='left',left_on='name',right_on='Country').shape

(218, 7)

In [23]:
# left: Keeping all rows from right Dataframe

co2.merge(forest,how='right',left_on='name',right_on='Country').shape

(204, 7)

## Option 3: 
Keeping all rows from bith dataframes. Missing values will be generated when both keys values do not match.

In [25]:
co2.merge(forest,how='outer',left_on='name',right_on='Country').shape

(225, 7)

## Fuzzy merging
Approximate string matching

### a) Merging cia and fragility

In [97]:
FragilityAll=pd.read_csv('https://github.com/Ciencia-de-datos-espaciales-2023-2/S7_IntegrarDatos/raw/main/Fragility.csv')
Fragility2019=FragilityAll.loc[FragilityAll.Year==2019,:"Total"]
Fragility2019

                        Country  Year  Total
1068                      YEMEN  2019  113.5
1069                    SOMALIA  2019  112.3
1070                SOUTH SUDAN  2019  112.2
1071                      SYRIA  2019  111.5
1072  CONGO DEMOCRATIC REPUBLIC  2019  110.2
...                         ...   ...    ...
1241                  AUSTRALIA  2019   19.7
1242                    DENMARK  2019   19.5
1243                SWITZERLAND  2019   18.7
1244                     NORWAY  2019   18.0
1245                    FINLAND  2019   16.9

[178 rows x 3 columns]

In [104]:
Onlycia=set(cia.Country)-set(Fragility2019.Country)
Onlyfragility=set(Fragility2019.Country)-set(cia.Country)

In [47]:
!pip install thefuzz

Requirement already satisfied: thefuzz in c:\users\patiy li yang\anaconda3\envs\ciencia_de_datos_espaciales\lib\site-packages (0.20.0)
Requirement already satisfied: rapidfuzz<4.0.0,>=3.0.0 in c:\users\patiy li yang\anaconda3\envs\ciencia_de_datos_espaciales\lib\site-packages (from thefuzz) (3.3.1)

In [110]:
from thefuzz import process as fz

# take a country from Onlyfragility 
# and return the most similar (>=87%) in Onlycia 
FragilityAll=pd.read_csv('https://github.com/Ciencia-de-datos-espaciales-2023-2/S7_IntegrarDatos/raw/main/Fragility.csv')
Fragility2019=FragilityAll.loc[FragilityAll.Year==2019,:"Total"]

[(f,fz.extractOne(f,Onlycia))for f in sorted(Onlyfragility) 
 if fz.extractOne(f,Onlycia)[1]>86]

[('BAHAMAS', ('BAHAMAS, THE', 90)),
 ('BRUNEI DARUSSALAM', ('BRUNEI', 90)),
 ('CONGO DEMOCRATIC REPUBLIC', ('CONGO, DEMOCRATIC REPUBLIC OF THE', 95)),
 ('GAMBIA', ('GAMBIA, THE', 90)),
 ('GUINEA BISSAU', ('GUINEA-BISSAU', 100)),
 ('ISRAEL AND WEST BANK', ('WEST BANK', 90)),
 ('MACEDONIA', ('NORTH MACEDONIA', 90)),
 ('MICRONESIA', ('MICRONESIA, FEDERATED STATES OF', 90)),
 ('SOUTH KOREA', ('KOREA, SOUTH', 95)),
 ('TURKEY', ('TURKEY (TURKIYE)', 90))]

In [116]:
#dictionary with most similar country names 
changesFragility={f:fz.extractOne(f, Onlycia)[0] 
                  for f in sorted(Onlyfragility) 
                  if fz.extractOne(f, Onlycia)[1] >=86}

#replacing names to their analogues in Onlycia
Fragility2019.Country.replace(to_replace=changesFragility,inplace=True)

In [120]:
fragilecia=Fragility2019.merge(cia)
fragilecia

,Country,Year,Total,name,co2,co2_date,region,ForestRev_gdp,ForestRev_date
0,YEMEN,2019,113.5,YEMEN,10158000.0,2019,MIDDLE EAST,0.04,2018
1,SOUTH SUDAN,2019,112.2,SOUTH SUDAN,1778000.0,2019,AFRICA,2.65,2015
2,"CONGO, DEMOCRATIC REPUBLIC OF THE",2019,110.2,"CONGO, DEMOCRATIC REPUBLIC OF THE",2653000.0,2019,AFRICA,8.72,2018
3,"CONGO, DEMOCRATIC REPUBLIC OF THE",2019,76.2,"CONGO, DEMOCRATIC REPUBLIC OF THE",2653000.0,2019,AFRICA,8.72,2018
4,"CONGO, DEMOCRATIC REPUBLIC OF THE",2019,40.5,"CONGO, DEMOCRATIC REPUBLIC OF THE",2653000.0,2019,AFRICA,8.72,2018
...,...,...,...,...,...,...,...,...,...
165,AUSTRALIA,2019,19.7,AUSTRALIA,417870000.0,2019,AUSTRALIA AND OCEANIA,0.13,2018
166,DENMARK,2019,19.5,DENMARK,33850000.0,2019,EUROPE,0.02,2018
167,SWITZERLAND,2019,18.7,SWITZERLAND,38739000.0,2019,EUROPE,0.01,2018
168,NORWAY,2019,18.0,NORWAY,36731000.0,2019,EUROPE,0.05,2018
169,FINLAND,2019,16.9,FINLAND,41996000.0,2019,EUROPE,0.36,2018

### b) Merging fragilecia and iso

In [124]:
isoLink='https://github.com/CienciaDeDatosEspacial/dataSets/raw/main/isodata.csv'
isoCodes=pd.read_csv(isoLink)
isoCodes

,Countryname,Officialstatename,InternetccTLD,iso2,iso3
0,Afghanistan,The Islamic Republic of Afghanistan,.af,AF,AFG
1,Ã…land Islands,Ã…land,.ax,AX,ALA
2,Albania,The Republic of Albania,.al,AL,ALB
3,Algeria,The People's Democratic Republic of Algeria,.dz,DZ,DZA
4,American Samoa,The Territory of American Samoa,.as,AS,ASM
...,...,...,...,...,...
244,Wallis and Futuna,The Territory of the Wallis and Futuna Islands,.wf,WF,WLF
245,Western Sahara,The Sahrawi Arab Democratic Republic,NaN,EH,ESH
246,Yemen,The Republic of Yemen,.ye,YE,YEM
247,Zambia,The Republic of Zambia,.zm,ZM,ZMB
248,Zimbabwe,The Republic of Zimbabwe,.zw,ZW,ZWE

In [132]:
Onlyiso=set(isoCodes.Countryname)-set(fragilecia.Country)
Onlyfragilecia=set(fragilecia.Country)-set(isoCodes.Countryname)

repl_fragilecia={f:fz.extractOne(f,Onlyiso)[0] for f in sorted(Onlyfragilecia)
 if fz.extractOne(f,Onlyiso)[1]>68 }

In [148]:
fragilecia.Country.replace(to_replace=repl_fragilecia,inplace=True)
fragciaiso=isoCodes.merge(fragilecia,left_on="Countryname",right_on="Country")

fragciaiso.drop(columns=['Country','name'],inplace=True)
fragciaiso.rename(columns={'Countryname':"Country",'Year':'fragility_date','Total':'fragility'},inplace=True)
 
fragciaiso

,Country,Officialstatename,InternetccTLD,iso2,iso3,fragility_date,fragility,co2,co2_date,region,ForestRev_gdp,ForestRev_date
0,Afghanistan,The Islamic Republic of Afghanistan,.af,AF,AFG,2019,105.0,7893000.0,2019,SOUTH ASIA,0.20,2018
1,Albania,The Republic of Albania,.al,AL,ALB,2019,58.9,3794000.0,2019,EUROPE,0.18,2018
2,Algeria,The People's Democratic Republic of Algeria,.dz,DZ,DZA,2019,75.4,151633000.0,2019,AFRICA,0.10,2018
3,Angola,The Republic of Angola,.ao,AO,AGO,2019,87.8,19362000.0,2019,AFRICA,0.36,2018
4,Antigua and Barbuda,Antigua and Barbuda,.ag,AG,ATG,2019,54.4,729000.0,2019,CENTRAL AMERICA AND THE CARIBBEAN,0.00,2018
...,...,...,...,...,...,...,...,...,...,...,...,...
163,Uzbekistan,The Republic of Uzbekistan,.uz,UZ,UZB,2019,75.7,102965000.0,2019,CENTRAL ASIA,0.00,2018
164,Viet Nam,The Socialist Republic of Viet Nam,.vn,VN,VNM,2019,66.1,249929000.0,2019,EAST AND SOUTHEAST ASIA,1.49,2018
165,Yemen,The Republic of Yemen,.ye,YE,YEM,2019,113.5,10158000.0,2019,MIDDLE EAST,0.04,2018
166,Zambia,The Republic of Zambia,.zm,ZM,ZMB,2019,85.7,6798000.0,2019,AFRICA,4.45,2018
167,Zimbabwe,The Republic of Zimbabwe,.zw,ZW,ZWE,2019,99.5,7902000.0,2019,AFRICA,1.61,2018

In [150]:
import os
fragciaiso.to_csv(os.path.join("data","FragilityCia_isos.csv"), index=False)